title: Summary Sheet Appendix
description: A github pages site for hosting the syllabus index for the LU AR/VR programme summary sheet
theme: just-the-docs

url: https://just-the-docs.github.io

search_enabled: false

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template